### PR TITLE
Added functionality to skip writing the tag used for filtering

### PR DESCRIPTION
**Pull request by mschrader15**
My [[roam/js/public-garden]] looks like:

```
- Index
    - Website Homepage
- Filter
    - Tagged With
        - Blog Post
            - write tag = false
```

where **write tag = false** instructs the code to skip writing lines with [[Blog Post]] to html

I am not set on the language of **write tag = false**. We could change it to something better or simply use an Action input.

### CODE REVIEW

**Comment by caffo** [comment]
Hi Max, thanks for the PR. The way we envisioned to handle this issue is to add the tag as a child block of `[[roam/js/public-garden/ignore]]` on the tagged page, since anything under it will not be rendered.

```
- [[roam/js/public-garden/ignore]]
  - [[Blog Post]]
```

We plan on adding more features using this structure (like a specific block to inject content to the head tag).

**Comment by caffo** [comment]
I will let @dvargas92495 decide on adding this to the project. I personally don't think it's necessary, but it may be good to have a more explicit way to do it.

**Comment by mschrader15** [comment]
@caffo :facepalm: I was confused with the Page vs Block language in Roam. Sounds like the existing [[roam/js/public-garden/ignore]] will suffice.

BTW I followed the "How is this website made" page on your website to build my own! Thanks for publishing it!

**Comment by mschrader15** [comment]
@caffo when I use the [[roam/js/public-garden/ignore]] method, the [[roam/js/public-garden/ignore]] is converted to HTML, as it contains the filter tag.

I don't think this behavior is desired, but should be an easy fix.

@dvargas92495 should I create an issue?

**Comment by caffo** [comment]
This is strange, it works for me. 

image

```
[[roam/js/public-garden/ignore]]
    -  Tags:: [[Website Page]]
![](https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2Frodrigofranco%2FiMcD3XierZ.png?alt=media&token=f2432a93-2c68-4f5a-b4a3-a5defeea0115)
### About Me
    - [[Whois]] — Who is Rodrigo Franco (aka Caffo)
    - [[Now]] — What I'm doing right now
    - [[LMN]] — Less, More and None
```
(I'm using document mode but it should work anyway)

**Comment by caffo** [comment]
Just to make sure I explained it properly, I have that in every page:

image

```
[[roam/js/public-garden/ignore]]
    -  Tags:: [[Website Page]]
Married, father of one. [INTJ](https://www.16personalities.com/intj-personality). Always trying to come up with tangibles from the intangible. Started as a [sysop](https://en.wikipedia.org/wiki/Sysop) and now owns a [small but glorious consulting company](http://flexcodellc.com/).
```

**Comment by dvargasfuertes** [comment]
> [[roam/js/public-garden/ignore]] method, the [[roam/js/public-garden/ignore]] is converted to HTML

ah yea it should probably not be included in the output, though I would expect this page to be empty. Why is the filter tag on the page?

**Comment by mschrader15** [comment]
@caffo thanks for the explanation, it's working for me now

@dvargas92495 I was confused about the usage of [[roam/js/public-garden/ignore]]. I interpreted the usage to be one where the block to skip is added to the [[roam/js/public-garden/ignore]] page itself.

I like the method of nesting blocks to ignore under the [[roam/js/public-garden/ignore]] on the target page, makes sense for building out additional features with this structure

**Comment by caffo** [comment]
Yeah, we need to document it better (with examples).  😄

**Pull request closed without merging**
